const CSR_BG = 'https://images.unsplash.com/photo-1569025690938-a00729c9e1f9?w=1600&q=70&fit=crop';

const CSR_INITIATIVES = [
  {
    icon: '🛤',
    title: '12 km Road',
    location: 'Saylem Region',
    desc: 'Birhan Coffee maintains a critical 12 km road in Saylem, enabling farmers to transport their coffee beans to processing centres efficiently and safely — directly reducing costs and improving profitability for smallholder families.',
    img: 'https://img2.chinadaily.com.cn/images/201809/05/5b8f1f27a310add1c69a5f29.jpeg',
    stat: '12km', statLabel: 'Road Maintained',
  },
  {
    icon: '🌉',
    title: 'Two Bridges',
    location: 'Saylem Streams',
    desc: "We constructed two small bridges over local streams, ensuring safe passage for villagers year-round — including during the rainy season when streams become impassable. Children can attend school and residents can reach healthcare facilities.",
    img: 'https://images.unsplash.com/photo-1513828583688-c52646db42da?w=600&q=80&fit=crop',
    stat: '2', statLabel: 'Bridges Built',
  },
  {
    icon: '📚',
    title: 'Farmer Education',
    location: 'All Regions',
    desc: 'We run regular training programmes covering sustainable farming techniques, modern agricultural methods, health, hygiene, and financial literacy. Our goal: equip farmers with knowledge that improves their productivity, income, and quality of life for generations.',
    img: 'https://blog.compassion.com/wp-content/uploads/2020/09/a-group-of-ethiopian-children-looking-up-at-the-camera-smiling.jpg',
    stat: '200+', statLabel: 'Farmers Trained',
  },
  {
    icon: '💰',
    title: 'Fair Premium Prices',
    location: 'All Partner Farms',
    desc: "We pay above-market premium prices directly to our 200+ smallholder farmers — no middlemen. This direct trade model ensures that the wealth generated by Ethiopia's extraordinary coffee reaches the communities that grow it.",
    img: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=600&q=80&fit=crop',
    stat: '3×', statLabel: 'Above Commodity Price',
  },
];

const IMPACT = [
  { n: '200+', l: 'Farming Families Supported' },
  { n: '12km', l: 'Road Infrastructure' },
  { n: '2', l: 'Bridges Constructed' },
  { n: '∞', l: 'Community Impact' },
];

export default function CSR() {
  return (
    <section id="csr" style={{ position: 'relative' }}>

      {/* Banner */}
      <div style={{
        position: 'relative', padding: 'clamp(60px,8vw,100px) clamp(20px,5vw,60px)',
        backgroundImage: `url(${CSR_BG})`,
        backgroundSize: 'cover', backgroundPosition: 'center',
        backgroundAttachment: 'fixed',
        overflow: 'hidden',
      }}>
        <div style={{
          position: 'absolute', inset: 0,
          background: 'linear-gradient(135deg, rgba(7,5,10,0.92) 0%, rgba(7,5,10,0.7) 100%)',
        }} />
        <div className="container" style={{ position: 'relative', textAlign: 'center' }}>
          <p className="section-label">Giving Back</p>
          <h2 className="section-title" style={{ marginBottom: 20 }}>
            Corporate <em>Social Responsibility</em>
          </h2>
          <div className="divider center" />
          <p style={{ fontFamily: 'DM Sans,sans-serif', fontWeight: 300, color: 'rgba(245,236,215,0.6)', maxWidth: 600, margin: '0 auto 60px', lineHeight: 1.8 }}>
            Growth that isn't shared isn't growth at all. Birhan Coffee's CSR programme at Saylem and beyond invests directly in the infrastructure, education, and livelihoods of the communities that make our coffee possible.
          </p>
          {/* Impact stats */}
          <div style={{ display: 'flex', justifyContent: 'center', gap: 64, flexWrap: 'wrap' }}>
            {IMPACT.map(({ n, l }) => (
              <div key={l} style={{ textAlign: 'center' }}>
                <div style={{ fontFamily: 'Cormorant Garamond,serif', fontSize: 'clamp(2rem,4vw,3rem)', fontWeight: 700, color: '#C27C3A', lineHeight: 1 }}>{n}</div>
                <div style={{ fontFamily: 'DM Sans,sans-serif', fontSize: '0.68rem', letterSpacing: '0.15em', textTransform: 'uppercase', color: 'rgba(245,236,215,0.45)', marginTop: 6 }}>{l}</div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Initiatives Grid */}
      <div style={{ padding: 'clamp(60px,8vw,100px) clamp(20px,5vw,60px)', background: '#0c0908' }}>
        <div className="container">
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 24 }}>
            {CSR_INITIATIVES.map(item => (
              <div key={item.title} style={{
                border: '1px solid rgba(245,236,215,0.08)',
                borderRadius: 4, overflow: 'hidden',
                background: 'rgba(255,255,255,0.02)',
                transition: 'border-color 0.3s',
                display: 'grid', gridTemplateColumns: '1fr 1fr',
              }}
                onMouseEnter={e => e.currentTarget.style.borderColor = 'rgba(194,124,58,0.25)'}
                onMouseLeave={e => e.currentTarget.style.borderColor = 'rgba(245,236,215,0.08)'}
              >
                <div style={{ padding: 32 }}>
                  <div style={{ fontSize: '2rem', marginBottom: 12 }}>{item.icon}</div>
                  <div style={{ fontFamily: 'DM Sans,sans-serif', fontSize: '0.65rem', letterSpacing: '0.18em', textTransform: 'uppercase', color: '#C27C3A', marginBottom: 8 }}>{item.location}</div>
                  <h4 style={{ fontFamily: 'Cormorant Garamond,serif', fontSize: '1.6rem', color: '#F5ECD7', marginBottom: 12 }}>{item.title}</h4>
                  <p style={{ fontFamily: 'DM Sans,sans-serif', fontWeight: 300, fontSize: '0.85rem', color: 'rgba(245,236,215,0.55)', lineHeight: 1.75, marginBottom: 20 }}>{item.desc}</p>
                  <div>
                    <div style={{ fontFamily: 'Cormorant Garamond,serif', fontSize: '2.4rem', fontWeight: 700, color: '#C27C3A', lineHeight: 1 }}>{item.stat}</div>
                    <div style={{ fontFamily: 'DM Sans,sans-serif', fontSize: '0.62rem', letterSpacing: '0.15em', textTransform: 'uppercase', color: 'rgba(245,236,215,0.3)', marginTop: 2 }}>{item.statLabel}</div>
                  </div>
                </div>
                <div style={{ overflow: 'hidden' }}>
                  <img src={item.img} alt={item.title} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Vision / Mission / Values */}
      <div style={{ padding: 'clamp(60px,8vw,100px) clamp(20px,5vw,60px)', background: '#07050a' }}>
        <div className="container">
          <div style={{ textAlign: 'center', marginBottom: 60 }}>
            <p className="section-label">Our Foundation</p>
            <h2 className="section-title">Vision · Mission · <em>Values</em></h2>
            <div className="divider center" />
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 2 }}>
            {[
              {
                label: 'Vision',
                title: 'Global Leadership',
                desc: 'To be a leading exporter of Ethiopian coffee beans globally, renowned for exceptional quality and corporate social responsibility.',
                icon: '🔭',
                bg: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=600&q=60',
              },
              {
                label: 'Mission',
                title: 'Empower & Export',
                desc: 'To produce and export high-quality Ethiopian coffee beans while empowering local farmers and promoting sustainable agricultural practices.',
                icon: '🎯',
                bg: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=60',
              },
              {
                label: 'Values',
                title: 'QSCI Framework',
                desc: null,
                values: [
                  { v: 'Quality', d: 'Highest grade beans, every batch.' },
                  { v: 'Sustainability', d: 'Eco-conscious at every step.' },
                  { v: 'Community', d: 'Farmers first, always.' },
                  { v: 'Integrity', d: 'Ethical business, full stop.' },
                ],
                icon: '⚖️',
                bg: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&q=60',
              },
            ].map(item => (
              <div key={item.label} style={{ position: 'relative', overflow: 'hidden', minHeight: 380 }}>
                <img src={item.bg} alt={item.label} style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover', opacity: 0.12 }} />
                <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(135deg, rgba(7,5,10,0.95), rgba(12,9,8,0.9))' }} />
                <div style={{ position: 'relative', padding: 40 }}>
                  <div style={{ fontSize: '2rem', marginBottom: 16 }}>{item.icon}</div>
                  <div style={{ fontFamily: 'DM Sans,sans-serif', fontSize: '0.65rem', letterSpacing: '0.25em', textTransform: 'uppercase', color: '#C27C3A', marginBottom: 8 }}>{item.label}</div>
                  <h3 style={{ fontFamily: 'Cormorant Garamond,serif', fontSize: '1.8rem', color: '#F5ECD7', marginBottom: 16 }}>{item.title}</h3>
                  <div style={{ width: 32, height: 1, background: '#C27C3A', marginBottom: 20 }} />
                  {item.desc && <p style={{ fontFamily: 'DM Sans,sans-serif', fontWeight: 300, fontSize: '0.88rem', color: 'rgba(245,236,215,0.6)', lineHeight: 1.75 }}>{item.desc}</p>}
                  {item.values && (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                      {item.values.map(({ v, d }) => (
                        <div key={v} style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                          <span style={{ color: '#C27C3A', marginTop: 2, flexShrink: 0 }}>✦</span>
                          <div>
                            <span style={{ fontFamily: 'Cormorant Garamond,serif', fontSize: '1.05rem', color: '#F5ECD7' }}>{v} </span>
                            <span style={{ fontFamily: 'DM Sans,sans-serif', fontSize: '0.8rem', color: 'rgba(245,236,215,0.45)' }}>— {d}</span>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
