import { createContext, useContext, useState } from 'react';

export const LANGUAGES = [
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'am', label: 'አማርኛ', flag: '🇪🇹' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
];

export const T = {
  en: {
    // Navbar
    home: 'Home', ourStory: 'Our Story', farmToCup: 'Farm to Cup',
    coffees: 'Coffees', aboutUs: 'About Us', contact: 'Contact',
    cart: 'Cart',
    // Hero
    heroLine1: 'From the', heroLine2: 'Ethiopian Highlands', heroLine3: 'To Your Cup',
    heroDesc: 'Birhan Coffee PLC — a top-100 Ethiopian coffee exporter — brings single-origin, traceable specialty beans from four legendary regions directly to global markets.',
    exploreCoffees: 'Explore Our Coffees →', farmJourney: 'Farm to Cup Journey',
    // About
    ourCompany: 'Our Company', fiveYears: 'Five Years of', purposefulGrowth: 'Purposeful Growth',
    workWithUs: 'Work With Us →',
    // Coffees
    singleOrigin: 'Single-Origin Specialty', ourCoffees: 'Our Coffees',
    fourOrigins: 'Four distinct Ethiopian origins. Fully traceable. Ethically sourced. Premium Arabica at its finest.',
    addToCart: 'Add to Cart', perBag: 'per 250g bag',
    // Contact
    getInTouch: 'Get In Touch', letsTalk: "Let's Talk", coffee: 'Coffee',
    sendMessage: 'Send Message ✦', yourName: 'Your Name', email: 'Email',
    company: 'Company / Organisation', message: 'Message',
    interestedIn: "I'm interested in",
    // Footer
    developedBy: 'Developed by Ezera Hailu & Matiyas Tesfaye',
    allRights: '© 2025 Birhan Coffee PLC. All rights reserved.',
    tagline: 'Addis Ababa · Ethiopia · Direct Trade',
    // General
    requestSample: 'Request a Sample →', learnMore: 'Learn More →',
    readMore: 'Read More →', viewDetails: 'View details →',
    // About
    ourCompanyLabel: 'Our Company',
    aboutTitle1: 'Five Years of', aboutTitle2: 'Purposeful Growth',
    aboutP1: 'Birhan Coffee PLC was established in 2019 with a simple but powerful conviction: exceptional Ethiopian coffee, delivered with integrity. Over five years we built strong relationships with over 200 local farmers, invested in sustainable farming, and opened our modern processing facility in Sebeta.',
    aboutP2: 'By 2022 we had expanded to international markets, earning recognition in the top 100 Ethiopian coffee exporters. Today, Birhan Coffee is synonymous with quality, sustainability, and community empowerment.',
    sustainableFarming: 'Sustainable Farming', sustainableFarmingDesc: 'Fair trade & eco-conscious practices at every stage',
    directRelationships: 'Direct Relationships', directRelationshipsDesc: '200+ farming families paid premium fair prices',
    recognisedQuality: 'Recognised Quality', recognisedQualityDesc: 'Top 100 Ethiopian coffee exporter since 2022',
    globalReach: 'Global Reach', globalReachDesc: 'Exporting premium Arabica to international markets',
    workWithUsCta: 'Work With Us →',
    ourFounder: 'Our Founder',
    founderTitle: 'Birhanu', founderTitleItalic: 'Lemi',
    founderRole: 'Founder & CEO, Birhan Coffee PLC',
    founderP1: "Born and raised in the lush highlands of Ethiopia, Birhanu Lemi spent 25 years building successful businesses before channelling his passion for his homeland's most famous export into Birhan Coffee PLC.",
    founderP2: "His founding vision was to blend Ethiopia's ancient coffee traditions with modern processing standards, paying fair prices that genuinely transform farmers' lives. Under his leadership, Birhan Coffee became a top-100 Ethiopian coffee exporter in just three years.",
    founderP3: 'Birhanu has received multiple national and international awards for sustainable farming and fair trade.',
    founderQuote: '"Every cup of Birhan Coffee must not only taste exceptional — it must support a brighter future for Ethiopian farmers."',
    yearsInBusiness: 'Years in Business',
    // Coffees
    singleOriginLabel: 'Single-Origin Specialty',
    ourCoffeesTitle: 'Our', ourCoffeesItalic: 'Coffees',
    coffeesDesc: 'Four distinct Ethiopian origins. Fully traceable. Ethically sourced. Premium Arabica at its finest.',
    perBagLabel: 'per 250g bag',
    addToCartBtn: 'Add to Cart',
    addBtn: 'Add',
    valueAdded: 'Value-Added Products',
    beyondGreenBean: 'Beyond the', beyondGreenBeanItalic: 'Green Bean',
    b2bLabel: 'B2B & Wholesale',
    bulkTitle: 'Looking to order in', bulkItalic: 'bulk?',
    bulkDesc: 'View our wholesale pricing tiers, use our interactive shipping calculator, and get a confirmed quote — all in one place.',
    viewWholesale: 'View Wholesale & Shipping →',
    // FarmToCup
    theJourney: 'The Journey',
    farmToCupTitle: 'From', farmToCupItalic: 'Farm to Cup',
    farmToCupDesc: 'Every cup of Birhan Coffee carries a story of careful stewardship across five critical stages — from seed to sack to your morning ritual.',
    // Team
    teamLabel: 'The People Behind the Cup',
    teamTitle: 'Our', teamTitleItalic: 'Team of Experts',
    teamDesc: 'Every step of the farm-to-export journey is overseen by dedicated specialists who share a passion for Ethiopian coffee excellence.',
    teamQuote: '"At Birhan Coffee, we are committed to producing and delivering the finest Ethiopian coffee beans while supporting local communities and promoting sustainable agricultural practices."',
    teamQuoteAuthor: '— Birhanu Lemi, Founder & CEO',
    // CSR
    givingBack: 'Giving Back',
    csrTitle: 'Corporate', csrTitleItalic: 'Social Responsibility',
    csrDesc: "Growth that isn't shared isn't growth at all. Birhan Coffee's CSR programme at Saylem and beyond invests directly in the infrastructure, education, and livelihoods of the communities that make our coffee possible.",
    ourFoundation: 'Our Foundation',
    vmvTitle: 'Vision · Mission ·', vmvItalic: 'Values',
    // Home pull-quote
    ourStrategy: 'Our Strategy',
    pullQuote: '"We deliver on time not only for the sake of customer satisfaction — we do this because it is our internal culture of doing things the right way."',
    pullQuoteAuthor: '— Birhan Coffee, Core Philosophy',
    // Testimonials
    partnerVoices: 'Partner Voices',
    whatPartnersSay: 'What Our', whatPartnersSayItalic: 'Partners Say',
    partnersDesc: 'Roasters, importers, and specialty buyers from across the globe — on what makes Birhan Coffee their trusted Ethiopian partner.',
    becomePartner: 'Become our next', becomePartnerItalic: 'partner roaster',
    becomePartnerDesc: 'Join roasters in 15+ countries who trust Birhan for their Ethiopian single-origin.',
    requestSamplesCta: 'Request Samples →',
    // Certifications
    trustStandards: 'Trust & Standards',
    certsTitle: 'Certifications', certsItalic: '& Awards',
    certsDesc: 'Every claim we make is backed by independent verification, certified processes, and a transparent paper trail.',
    awardTimeline: 'Award', awardTimelineItalic: 'Timeline',
    certDocsNote: 'Need certification documents for due diligence? We provide full documentation to verified partners.',
    requestDocuments: 'Request Documents →',
    // Gallery
    visualStory: 'Visual Story',
    galleryTitle: 'Farm to Cup', galleryItalic: 'Gallery',
    galleryDesc: 'Real photographs from our farms, processing facilities, team, and the Ethiopian coffee landscape.',
    // Blog
    knowledgeStories: 'Knowledge & Stories',
    blogTitle: 'The Coffee', blogItalic: 'Journal',
    blogDesc: 'Origins, processing, culture, and the science behind exceptional Ethiopian coffee.',
    readArticle: 'Read Article →',
    readMoreLink: 'Read More →',
    subscribe: 'Subscribe',
    newsletterTitle: 'Get new articles in your', newsletterItalic: 'inbox',
    newsletterDesc: 'Origins deep-dives, processing guides, and stories from the Ethiopian highlands.',
    // FAQ
    commonQuestions: 'Common Questions',
    faqTitle: 'Frequently Asked', faqItalic: 'Questions',
    faqDesc: 'Shipping, minimum orders, certifications, samples — everything buyers and partners ask most.',
    stillQuestion: 'Still have a', stillQuestionItalic: 'question?',
    stillQuestionDesc: 'Our team responds within 24 hours, every day of the week.',
    emailUs: '✉️ Email Us',
    callUs: '📞 Call Us',
    // Sample Request
    freeSamples: 'Free Samples',
    sampleTitle: 'Request a', sampleItalic: 'Sample',
    sampleDesc: 'We ship free samples to verified roasters and importers worldwide. Taste before you commit — that\'s our promise.',
    sampleSentTitle: 'Request', sampleSentItalic: 'Sent!',
    sampleSentDesc: 'Your email client should have opened with your request. We\'ll respond within 24 hours.',
    backHome: 'Back Home',
    sendRequest: 'Send Request →',
    additionalNotes: 'Additional Notes',
    selectOrigins: 'Select Origins',
    productFormat: 'Product Format',
    expectedVolume: 'Expected Volume',
    freeSamplesNote: 'Free samples shipped to verified businesses. Response within 24 hours.',
    // Wholesale
    b2bWholesale: 'B2B & Wholesale',
    wholesaleTitle: 'Wholesale', wholesaleItalic: 'Pricing & Shipping',
    wholesaleDesc: 'Transparent pricing for roasters, importers, and distributors. All prices FOB Addis Ababa.',
    pricingTiers: 'Pricing', pricingTiersItalic: 'Tiers',
    estimateOrder: 'Estimate Your Order',
    shippingCalc: 'Shipping', shippingCalcItalic: 'Calculator',
    shippingCalcDesc: 'Indicative CIF pricing. Final quotes confirmed by our logistics team within 24 hours.',
    requestQuote: 'Request Confirmed Quote →',
    requestSampleFirst: 'Request Free Sample First',
    readyFirstOrder: 'Ready to place your', readyFirstOrderItalic: 'first order?',
    readyFirstOrderDesc: 'Our team responds within 24 hours with a confirmed quote and sample offer.',
    emailTeam: '✉️ Email Our Team',
    whatsappUs: '💬 WhatsApp Us',
    // StepPage
    backToOverview: '← Back to overview',
    pageNotFound: 'Page not found',
  },
  am: {
    // Navbar
    home: 'መነሻ', ourStory: 'ታሪካችን', farmToCup: 'ከእርሻ እስከ ኩባያ',
    coffees: 'ቡናዎቻችን', aboutUs: 'ስለ እኛ', contact: 'ያግኙን',
    cart: 'ጋሪ',
    // Hero
    heroLine1: 'ከ', heroLine2: 'የኢትዮጵያ ደጋዎች', heroLine3: 'እስከ ኩባያዎ',
    heroDesc: 'ብርሃን ቡና ኃ.የተ.የግ.ማ — ከኢትዮጵያ ምርጥ 100 ቡና ላኪዎች አንዱ — ከአራት ታዋቂ ክልሎች ቀጥታ ወደ ዓለም ገበያ ልዩ ቡና ያቀርባል።',
    exploreCoffees: 'ቡናዎቻችንን ያስሱ →', farmJourney: 'ከእርሻ እስከ ኩባያ ጉዞ',
    // About
    ourCompany: 'ኩባንያችን', fiveYears: 'አምስት ዓመታት', purposefulGrowth: 'ዓላማ ያለው ዕድገት',
    workWithUs: 'ከእኛ ጋር ይስሩ →',
    // Coffees
    singleOrigin: 'ነጠላ-ምንጭ ልዩ ቡና', ourCoffees: 'ቡናዎቻችን',
    fourOrigins: 'አራት የተለያዩ የኢትዮጵያ ምንጮች። ሙሉ ተከታታይነት። በሥነ-ምግባር የተሰበሰበ። ምርጥ አረቢካ።',
    addToCart: 'ወደ ጋሪ ጨምር', perBag: 'በ250ግ ከረጢት',
    // Contact
    getInTouch: 'ያግኙን', letsTalk: 'ስለ', coffee: 'ቡና እናውራ',
    sendMessage: 'መልዕክት ላክ ✦', yourName: 'ስምዎ', email: 'ኢሜይል',
    company: 'ኩባንያ / ድርጅት', message: 'መልዕክት',
    interestedIn: 'ፍላጎቴ',
    // Footer
    developedBy: 'የተሰራው በ ኤዘራ ሃይሉ እና ማቲያስ ተስፋዬ',
    allRights: '© 2025 ብርሃን ቡና ኃ.የተ.የግ.ማ። መብቱ በሕግ የተጠበቀ ነው።',
    tagline: 'አዲስ አበባ · ኢትዮጵያ · ቀጥታ ንግድ',
    // General
    requestSample: 'ናሙና ይጠይቁ →', learnMore: 'ተጨማሪ ይወቁ →',
    readMore: 'ተጨማሪ ያንብቡ →', viewDetails: 'ዝርዝር ይመልከቱ →',
    // About
    ourCompanyLabel: 'ኩባንያችን',
    aboutTitle1: 'አምስት ዓመታት', aboutTitle2: 'ዓላማ ያለው ዕድገት',
    aboutP1: 'ብርሃን ቡና ኃ.የተ.የግ.ማ በ2019 ዓ.ም ተቋቁሟል። ከ200 በላይ ገበሬዎች ጋር ጠንካራ ግንኙነት ፈጥረናል፣ ዘላቂ እርሻን ደግፈናል፣ እና ዘመናዊ ማቀነባበሪያ ፋብሪካ ሰበታ ውስጥ ከፍተናል።',
    aboutP2: 'እ.ኤ.አ. 2022 ወደ ዓለም አቀፍ ገበያ ተስፋፍተናል፣ ከኢትዮጵያ ምርጥ 100 ቡና ላኪዎች አንዱ ሆነናል። ዛሬ ብርሃን ቡና ጥራት፣ ዘላቂነት እና የማህበረሰብ ብቃት ማሳደጊያ ምልክት ሆኗል።',
    sustainableFarming: 'ዘላቂ እርሻ', sustainableFarmingDesc: 'ፍትሃዊ ንግድ እና 친환경 ልምዶች',
    directRelationships: 'ቀጥታ ግንኙነቶች', directRelationshipsDesc: '200+ የገበሬ ቤተሰቦች ፍትሃዊ ዋጋ ይከፈላቸዋል',
    recognisedQuality: 'የታወቀ ጥራት', recognisedQualityDesc: 'ከ2022 ጀምሮ ምርጥ 100 ኢትዮጵያዊ ቡና ላኪ',
    globalReach: 'ዓለም አቀፍ ተደራሽነት', globalReachDesc: 'ምርጥ አረቢካ ወደ ዓለም አቀፍ ገበያ ይላካል',
    workWithUsCta: 'ከእኛ ጋር ይስሩ →',
    ourFounder: 'መስራቻችን',
    founderTitle: 'ብርሃኑ', founderTitleItalic: 'ለሚ',
    founderRole: 'መስራች እና ዋና ስራ አስፈፃሚ፣ ብርሃን ቡና ኃ.የተ.የግ.ማ',
    founderP1: 'ብርሃኑ ለሚ በኢትዮጵያ ደጋዎች ተወልዶ ያደገ ሲሆን ለ25 ዓመታት ስኬታማ ንግዶችን ካካሄደ በኋላ ለሀገሩ ታዋቂ ምርት ያለውን ፍቅር ወደ ብርሃን ቡና ኃ.የተ.የግ.ማ አዞረ።',
    founderP2: 'የእርሱ ራዕይ የኢትዮጵያን ጥንታዊ የቡና ወጎች ከዘመናዊ ማቀነባበሪያ ደረጃዎች ጋር ማዋሃድ ነበር። በእርሱ አመራር ብርሃን ቡና በሦስት ዓመት ውስጥ ምርጥ 100 ኢትዮጵያዊ ቡና ላኪ ሆነ።',
    founderP3: 'ብርሃኑ ለዘላቂ እርሻ እና ፍትሃዊ ንግድ ብዙ ሀገራዊ እና ዓለም አቀፍ ሽልማቶችን ተቀብሏል።',
    founderQuote: '"የብርሃን ቡና እያንዳንዱ ኩባያ ልዩ ጣዕም ብቻ ሳይሆን ለኢትዮጵያ ገበሬዎች ብሩህ ወደፊት መደገፍ አለበት።"',
    yearsInBusiness: 'ዓመታት በንግድ',
    // Coffees
    singleOriginLabel: 'ነጠላ-ምንጭ ልዩ ቡና',
    ourCoffeesTitle: 'ቡናዎቻችን', ourCoffeesItalic: '',
    coffeesDesc: 'አራት የተለያዩ የኢትዮጵያ ምንጮች። ሙሉ ተከታታይነት። በሥነ-ምግባር የተሰበሰበ። ምርጥ አረቢካ።',
    perBagLabel: 'በ250ግ ከረጢት',
    addToCartBtn: 'ወደ ጋሪ ጨምር',
    addBtn: 'ጨምር',
    valueAdded: 'ተጨማሪ ዋጋ ያላቸው ምርቶች',
    beyondGreenBean: 'ከ', beyondGreenBeanItalic: 'አረንጓዴ ቡና ባሻገር',
    b2bLabel: 'B2B እና ጅምላ',
    bulkTitle: 'በጅምላ ማዘዝ', bulkItalic: 'ይፈልጋሉ?',
    bulkDesc: 'የጅምላ ዋጋ ደረጃዎቻችንን ይመልከቱ፣ የጭነት ካልኩሌተራችንን ይጠቀሙ፣ እና ዋጋ ያግኙ።',
    viewWholesale: 'ጅምላ እና ጭነት ይመልከቱ →',
    // FarmToCup
    theJourney: 'ጉዞው',
    farmToCupTitle: 'ከ', farmToCupItalic: 'እርሻ እስከ ኩባያ',
    farmToCupDesc: 'የብርሃን ቡና እያንዳንዱ ኩባያ ከዘር እስከ ኩባያዎ ድረስ ባሉ አምስት ወሳኝ ደረጃዎች ላይ ጥንቃቄ የተሞላበት ታሪክ ይዟል።',
    // Team
    teamLabel: 'ከኩባያ በስተጀርባ ያሉ ሰዎች',
    teamTitle: 'የእኛ', teamTitleItalic: 'የባለሙያዎች ቡድን',
    teamDesc: 'ከእርሻ እስከ ወደ ውጭ ወደ ሚላክ ጉዞ እያንዳንዱ ደረጃ ለኢትዮጵያ ቡና ልቀት ፍቅር ያላቸው ባለሙያዎች ይቆጣጠሩታል።',
    teamQuote: '"በብርሃን ቡና ምርጥ የኢትዮጵያ ቡና ፍሬዎችን ለማምረት እና ለማቅረብ ቁርጠኞች ነን — ማህበረሰቦቻችንን እየደገፍን እና ዘላቂ የግብርና ልምዶችን እያስፋፋን።"',
    teamQuoteAuthor: '— ብርሃኑ ለሚ፣ መስራች እና ዋና ስራ አስፈፃሚ',
    // CSR
    givingBack: 'መልሶ መስጠት',
    csrTitle: 'ኮርፖሬት', csrTitleItalic: 'ማህበራዊ ኃላፊነት',
    csrDesc: 'ያልተጋራ ዕድገት ዕድገት አይደለም። የብርሃን ቡና CSR ፕሮግራም ቡናችንን ሊሆን ያስቻሉ ማህበረሰቦች ሕይወት ላይ ቀጥታ ኢንቨስት ያደርጋል።',
    ourFoundation: 'መሠረታችን',
    vmvTitle: 'ራዕይ · ተልዕኮ ·', vmvItalic: 'እሴቶች',
    ourStrategy: 'የእኛ ዘዴ',
    pullQuote: '"እኛ ጊዜያዊ ብቃት ላይ ብቻ እንሳበቅም — እሱ የምንደርሰው እውነተኛ ባህርይ ነው።"',
    pullQuoteAuthor: '— ብርሃን ቡና, ዋና ፍላጎት',
    partnerVoices: 'የባለጋራ ድምፆች',
    whatPartnersSay: 'የእኛ አብረኞች የሚሉት',
    partnersDesc: 'ከዓለም አቀፍ ዙሪያ የሚመጡ ሮስተሮች፣ ኢምፖርተሮችና የስፔሻልቲ አገልጋዮች — የብርሃን ቡናን ለምን እሱ የታመነ የኢትዮጵያ አብራሪ እንደሆነ ይናገራሉ።',
    becomePartner: 'የተጨማሪ አብራሪ ይሁኑ',
    becomePartnerItalic: 'አብራሪ',
    becomePartnerDesc: 'ከ15+ አገራት ጋር የሚስሩ ሮስተሮችን ይቀላቀሉ።',
    requestSamplesCta: 'ናሙናዎችን ይጠይቁ →',
    trustStandards: 'እምነት እና መለኪያዎች',
    certsTitle: 'ማረጋገጫዎች',
    certsItalic: '& ሽልማቶች',
    certsDesc: 'እያንዳንዱ እግዚአብሔር የምንለው በነጻ ብረታ የተረጋገጠ የስራ ሂደት እና ግልጽ የስራ ሰነድ ነው።',
    awardTimeline: 'የሽልማት',
    awardTimelineItalic: 'ጊዜ መስመር',
    certDocsNote: 'በሚፈለጉት ጊዜ የማረጋገጫ ሰነዶችን ለተረጋጋ አብራሪዎች እንሰጣለን።',
    requestDocuments: 'ሰነዶችን ይጠይቁ →',
    visualStory: 'ቪዙዋል ታሪክ',
    galleryTitle: 'ከእርሻ እስከ ኩባያ',
    galleryItalic: 'ጋለሪ',
    galleryDesc: 'ከእርሻ እስከ ኩባያ ድረስ የሚያዩ እውነተኛ ፎቶግራፎች።',
    knowledgeStories: 'እውቀት እና ታሪኮች',
    blogTitle: 'የቡናው ጉዞ',
    blogItalic: 'ጂርናል',
    blogDesc: 'ምንጮች፣ ሂደቶች፣ ባህላዊ ጉዳዮች እና የኢትዮጵያ ከፍተኛ ቡና ስለ ምን ይህ እንደሆነ እንገልጻለን።',
    readArticle: 'ዘገባውን ይያዙ →',
    readMoreLink: 'ተጨማሪ ያንብቡ →',
    subscribe: 'ይመዝገቡ',
    newsletterTitle: 'አዳዲስ ጽሑፎችን ወደ',
    newsletterItalic: 'ኢንቦክስ',
    newsletterDesc: 'የምንጭ ማብራሪያዎች፣ የሂደት መመሪያዎችን እና ከኢትዮጵያ የከተማው ከፍተኛ ቡና ታሪኮችን ይውሰዱ።',
    commonQuestions: 'ብዙ የሚጠየቁ ጥያቄዎች',
    faqTitle: 'ብዙ ጊዜ የሚጠየቁ',
    faqItalic: 'ጥያቄዎች',
    faqDesc: 'ሻጭ፣ ከፍተኛ ትዕዛዝ፣ ማረጋገጫዎች፣ ናሙናዎች — የጥያቄ እንዲሁ ይጠየቁታሉ።',
    stillQuestion: 'ጥያቄ አለዎት',
    stillQuestionItalic: 'ጥያቄ?',
    stillQuestionDesc: 'ቡድናችን በ24 ሰዓት ውስጥ ይመልሳል፣ የቀን ሁሉ እንዲሁም።',
    emailUs: '✉️ ኢሜይል ይላኩ',
    callUs: '📞 ይደውሉን',
    freeSamples: 'ነጻ ናሙናዎች',
    sampleTitle: 'ናሙና ይጠይቁ',
    sampleItalic: 'ምርት',
    sampleDesc: 'እንግድ ሮስተሮችን እና ኢምፖርተሮችን ወደ ዓለም አቀፍ ደረጃ ነጻ ናሙና እንልክ። ከዚህ በፊት እንዲያስተዋውቁ ይሞክሩ።',
    sampleSentTitle: 'ትዕዛዝ',
    sampleSentItalic: 'ተልኳል!',
    sampleSentDesc: 'ኢሜይል እባክዎን ከእኛ ጋር ይክፈቱ። በ24 ሰዓት ውስጥ እናገልግላለን።',
    backHome: 'ወደ መነሻ ተመለስ',
    sendRequest: 'ልክ ጠይቅ →',
    additionalNotes: 'ተጨማሪ ማስታወቂያዎች',
    selectOrigins: 'ምንጮችን ይምረጡ',
    productFormat: 'የምርት ቅርጸ ተከታታይ',
    expectedVolume: 'የተጠበቀ ብዛት',
    freeSamplesNote: 'ናሙናዎች ለተረጋጋ ቢዝነስ ይላካሉ። በ24 ሰዓት ውስጥ መልስ ይሰጣል።',
    b2bWholesale: 'B2B እና ጅምላ',
    wholesaleTitle: 'ጅምላ',
    wholesaleItalic: 'ዋጋ እና ጭነት',
    wholesaleDesc: 'የሮስተሮች፣ ኢምፖርተሮች እና ደርምዋንዎች ግልጽ ዋጋ እና መለኪያዎች። ሁሉም ዋጋዎች FOB አዲስ አበባ ናቸው።',
    pricingTiers: 'የዋጋ ደረጃዎች',
    estimateOrder: 'የትዕዛዝ እሴት',
    shippingCalc: 'የጭነት ካልኩሌተር',
    shippingCalcItalic: 'የጭነት',
    shippingCalcDesc: 'የCIF ቅናሽ ዋጋ ዝርዝር። የመጨረሻ ዋጋ በ24 ሰዓት ውስጥ የሎጂስቲክስ ቡድን ይደገፋል።',
    requestQuote: 'የታወቀ ወጪ ይጠይቁ →',
    requestSampleFirst: 'የነጻ ናሙና እድል ይጠይቁ',
    readyFirstOrder: 'በመጀመሪያው ትዕዛዝዎ',
    readyFirstOrderItalic: 'ዝግጁነት?',
    readyFirstOrderDesc: 'ቡድናችን በ24 ሰዓት ውስጥ ታዋቂ ወጪ እና ናሙና ይሰጣል።',
    emailTeam: '✉️ ወደ ቡድን ኢሜይል ይላኩ',
    whatsappUs: '💬 በWhatsApp ይገናኙ',
    backToOverview: '← ወደ እይታ ተመለስ',
    pageNotFound: 'ገፅ አልተገኘም',
  },
  fr: {
    // Navbar
    home: 'Accueil', ourStory: 'Notre Histoire', farmToCup: 'De la Ferme à la Tasse',
    coffees: 'Nos Cafés', aboutUs: 'À Propos', contact: 'Contact',
    cart: 'Panier',
    // Hero
    heroLine1: 'Des', heroLine2: 'Hauts Plateaux Éthiopiens', heroLine3: 'À Votre Tasse',
    heroDesc: "Birhan Coffee PLC — l'un des 100 meilleurs exportateurs de café éthiopien — apporte des grains de spécialité traçables de quatre régions légendaires directement aux marchés mondiaux.",
    exploreCoffees: 'Explorer Nos Cafés →', farmJourney: 'Voyage de la Ferme à la Tasse',
    // About
    ourCompany: 'Notre Entreprise', fiveYears: 'Cinq Ans de', purposefulGrowth: 'Croissance Purposive',
    workWithUs: 'Travailler Avec Nous →',
    // Coffees
    singleOrigin: 'Spécialité Mono-Origine', ourCoffees: 'Nos Cafés',
    fourOrigins: "Quatre origines éthiopiennes distinctes. Entièrement traçables. Sourcés éthiquement. Le meilleur Arabica.",
    addToCart: 'Ajouter au Panier', perBag: 'par sachet 250g',
    // Contact
    getInTouch: 'Nous Contacter', letsTalk: 'Parlons', coffee: 'Café',
    sendMessage: 'Envoyer le Message ✦', yourName: 'Votre Nom', email: 'Email',
    company: 'Entreprise / Organisation', message: 'Message',
    interestedIn: "Je suis intéressé par",
    // Footer
    developedBy: 'Développé par Ezera Hailu & Matiyas Tesfaye',
    allRights: '© 2025 Birhan Coffee PLC. Tous droits réservés.',
    tagline: 'Addis-Abeba · Éthiopie · Commerce Direct',
    // General
    requestSample: 'Demander un Échantillon →', learnMore: 'En Savoir Plus →',
    readMore: 'Lire la Suite →', viewDetails: 'Voir les Détails →',
    // About
    ourCompanyLabel: 'Notre Entreprise',
    aboutTitle1: 'Cinq Ans de', aboutTitle2: 'Croissance Purposive',
    aboutP1: "Birhan Coffee PLC a été fondée en 2019 avec une conviction simple mais puissante : un café éthiopien exceptionnel, livré avec intégrité. En cinq ans, nous avons noué des relations solides avec plus de 200 agriculteurs locaux, investi dans une agriculture durable et ouvert notre installation de traitement moderne à Sebeta.",
    aboutP2: "En 2022, nous nous sommes étendus aux marchés internationaux, obtenant la reconnaissance parmi les 100 meilleurs exportateurs de café éthiopiens. Aujourd'hui, Birhan Coffee est synonyme de qualité, de durabilité et d'autonomisation des communautés.",
    sustainableFarming: 'Agriculture Durable', sustainableFarmingDesc: 'Pratiques équitables et éco-responsables à chaque étape',
    directRelationships: 'Relations Directes', directRelationshipsDesc: '200+ familles d’agriculteurs payées à des prix équitables',
    recognisedQuality: 'Qualité Reconnue', recognisedQualityDesc: 'Top 100 exportateurs de café éthiopien depuis 2022',
    globalReach: 'Portée Mondiale', globalReachDesc: 'Exportation d’Arabica premium vers les marchés internationaux',
    workWithUsCta: 'Travailler Avec Nous →',
    ourFounder: 'Notre Fondateur',
    founderTitle: 'Birhanu', founderTitleItalic: 'Lemi',
    founderRole: 'Fondateur & PDG, Birhan Coffee PLC',
    founderP1: "Né et élevé dans les hauts plateaux luxuriants d’Éthiopie, Birhanu Lemi a passé 25 ans à bâtir des entreprises prospères avant de canaliser sa passion pour l’exportation la plus célèbre de sa patrie dans Birhan Coffee PLC.",
    founderP2: "Sa vision fondatrice était de mélanger les traditions ancestrales du café éthiopien avec des normes de traitement modernes, en payant des prix équitables qui transforment véritablement la vie des agriculteurs. Sous sa direction, Birhan Coffee est devenu un exportateur top-100 en seulement trois ans.",
    founderP3: 'Birhanu a reçu de nombreux prix nationaux et internationaux pour l’agriculture durable et le commerce équitable.',
    founderQuote: '"Chaque tasse de Birhan Coffee doit non seulement avoir un goût exceptionnel — elle doit soutenir un avenir meilleur pour les agriculteurs éthiopiens."',
    yearsInBusiness: 'Ans en Affaires',
    // Coffees
    singleOriginLabel: 'Spécialité Mono-Origine',
    ourCoffeesTitle: 'Nos', ourCoffeesItalic: 'Cafés',
    coffeesDesc: 'Quatre origines éthiopiennes distinctes. Entièrement traçables. Sourçés éthiquement. Le meilleur Arabica.',
    perBagLabel: 'par sachet 250g',
    addToCartBtn: 'Ajouter au Panier',
    addBtn: 'Ajouter',
    valueAdded: 'Produits à Valeur Ajoutée',
    beyondGreenBean: 'Au-delà du', beyondGreenBeanItalic: 'Grain Vert',
    b2bLabel: 'B2B & Vente en Gros',
    bulkTitle: 'Vous souhaitez commander en', bulkItalic: 'gros ?',
    bulkDesc: 'Consultez nos niveaux de prix de gros, utilisez notre calculateur d’expédition interactif et obtenez un devis confirmé — le tout en un seul endroit.',
    viewWholesale: 'Voir Vente en Gros & Expédition →',
    // FarmToCup
    theJourney: 'Le Voyage',
    farmToCupTitle: 'De la', farmToCupItalic: 'Ferme à la Tasse',
    farmToCupDesc: 'Chaque tasse de Birhan Coffee porte une histoire de gestion attentive à travers cinq étapes critiques — de la graine au sac jusqu’à votre rituel matinal.',
    // Team
    teamLabel: 'Les Personnes Derrière la Tasse',
    teamTitle: 'Notre', teamTitleItalic: 'Équipe d’Experts',
    teamDesc: 'Chaque étape du voyage de la ferme à l’exportation est supervisée par des spécialistes dédiés qui partagent une passion pour l’excellence du café éthiopien.',
    teamQuote: '"Chez Birhan Coffee, nous nous engageons à produire et livrer les meilleurs grains de café éthiopiens tout en soutenant les communautés locales et en promouvant des pratiques agricoles durables."',
    teamQuoteAuthor: '— Birhanu Lemi, Fondateur & PDG',
    // CSR
    givingBack: 'Redonner',
    csrTitle: 'Responsabilité', csrTitleItalic: 'Sociale des Entreprises',
    csrDesc: "Une croissance qui n'est pas partagée n'est pas une croissance. Le programme RSE de Birhan Coffee à Saylem et au-delà investit directement dans l'infrastructure, l'éducation et les moyens de subsistance des communautés.",
    ourFoundation: 'Notre Fondation',
    vmvTitle: 'Vision · Mission ·', vmvItalic: 'Valeurs',
    ourStrategy: 'Notre Stratégie',
    pullQuote: '"Nous livrons à temps non pas seulement pour la satisfaction du client — c’est parce que c’est notre culture interne de faire les choses correctement."',
    pullQuoteAuthor: '— Birhan Coffee, Philosophie Centrale',
    partnerVoices: 'Voix de Partenaires',
    whatPartnersSay: 'Ce que disent nos',
    partnersDesc: 'Torréfacteurs, importateurs et acheteurs de spécialité du monde entier — sur ce qui fait de Birhan Coffee leur partenaire éthiopien de confiance.',
    becomePartner: 'Devenez notre prochain',
    becomePartnerItalic: 'partenaire',
    becomePartnerDesc: 'Rejoignez les torréfacteurs de plus de 15 pays qui font confiance à Birhan pour leur mono-origine éthiopien.',
    requestSamplesCta: 'Demandez des Échantillons →',
    trustStandards: 'Confiance & Normes',
    certsTitle: 'Certifications',
    certsItalic: '& Récompenses',
    certsDesc: 'Chaque affirmation est étayée par une vérification indépendante, des processus certifiés et une traçabilité transparente.',
    awardTimeline: 'Chronologie',
    awardTimelineItalic: 'des Récompenses',
    certDocsNote: 'Besoin des documents de certification pour la due diligence ? Nous fournissons des documents complets aux partenaires vérifiés.',
    requestDocuments: 'Demander des Documents →',
    visualStory: 'Histoire Visuelle',
    galleryTitle: 'De la Ferme à la',
    galleryItalic: 'Galerie',
    galleryDesc: 'Photos réelles de nos fermes, installations de traitement, équipe et paysage caféier éthiopien.',
    knowledgeStories: 'Connaissances & Histoires',
    blogTitle: 'Le Journal',
    blogItalic: 'du Café',
    blogDesc: 'Origines, traitement, culture et la science derrière le café éthiopien exceptionnel.',
    readArticle: 'Lire l’Article →',
    readMoreLink: 'Lire la Suite →',
    subscribe: 'S’abonner',
    newsletterTitle: 'Recevez de nouveaux articles dans votre',
    newsletterItalic: 'boîte de réception',
    newsletterDesc: 'Analyses d’origine, guides de traitement et histoires des hauts plateaux éthiopiens.',
    commonQuestions: 'Questions Fréquentes',
    faqTitle: 'Questions',
    faqItalic: 'Fréquentes',
    faqDesc: 'Expédition, commandes minimales, certifications, échantillons — tout ce que les acheteurs et partenaires demandent le plus.',
    stillQuestion: 'Vous avez encore',
    stillQuestionItalic: 'une question ?',
    stillQuestionDesc: 'Notre équipe répond sous 24 heures, tous les jours de la semaine.',
    emailUs: '✉️ Écrivez-nous',
    callUs: '📞 Appelez-nous',
    freeSamples: 'Échantillons Gratuits',
    sampleTitle: 'Demandez un',
    sampleItalic: 'Échantillon',
    sampleDesc: 'Nous expédions des échantillons gratuits aux torréfacteurs et importateurs vérifiés dans le monde entier. Goûtez avant de vous engager — c’est notre promesse.',
    sampleSentTitle: 'Demande',
    sampleSentItalic: 'Envoyée !',
    sampleSentDesc: 'Votre client email devrait s’être ouvert avec votre demande. Nous répondrons sous 24 heures.',
    backHome: 'Retour à l’Accueil',
    sendRequest: 'Envoyer la Demande →',
    additionalNotes: 'Notes Supplémentaires',
    selectOrigins: 'Sélectionnez les Origines',
    productFormat: 'Format du Produit',
    expectedVolume: 'Volume Attendu',
    freeSamplesNote: 'Échantillons gratuits expédiés aux entreprises vérifiées. Réponse dans les 24 heures.',
    b2bWholesale: 'B2B & Vente en Gros',
    wholesaleTitle: 'Tarification',
    wholesaleItalic: '& Expédition',
    wholesaleDesc: 'Tarification transparente pour torréfacteurs, importateurs et distributeurs. Tous les prix sont FOB Addis-Abeba.',
    pricingTiers: 'Niveaux',
    estimateOrder: 'Estimer la Commande',
    shippingCalc: 'Calculateur',
    shippingCalcItalic: 'd’Expédition',
    shippingCalcDesc: 'Tarifs CIF indicatifs. Devis finaux confirmés par notre équipe logistique sous 24 heures.',
    requestQuote: 'Demander un Devis Confirmé →',
    requestSampleFirst: 'Demandez d’abord un Échantillon Gratuit',
    readyFirstOrder: 'Prêt pour votre',
    readyFirstOrderItalic: 'première commande ?',
    readyFirstOrderDesc: 'Notre équipe répond sous 24 heures avec un devis confirmé et une offre d’échantillon.',
    emailTeam: '✉️ Envoyez un Email à Notre Équipe',
    whatsappUs: '💬 Contactez-nous sur WhatsApp',
    backToOverview: '← Retour à la vue d’ensemble',
    pageNotFound: 'Page non trouvée',
  },
};

const LangContext = createContext({ lang: 'en', setLang: () => {}, t: T.en });

export function LangProvider({ children }) {
  const [lang, setLang] = useState('en');
  return (
    <LangContext.Provider value={{ lang, setLang, t: T[lang] }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}

